spring.application.name=spring

spring.datasource.url=jdbc:mysql://localhost:3306/childsync-db
spring.datasource.username=root
spring.datasource.password=1209429855

spring.jpa.hibernate.ddl-auto=none